### ISSUE TITLE
Add instructions on how to push data up to Couch

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-jsonapi-docs#1]

**Comment by Gaurav0** [comment]
The following worked for me:
1. git clone this repo
2. ~~Merge in https://github.com/ember-learn/ember-jsonapi-docs/pull/2~~
3. Install CouchDb
4. Create a database 'docs'
5. Set environment variable COUCH_URL to http://127.0.0.1:5984/docs
6. Set environment variables
   - AWS_ACCESS_KEY_ID
   - AWS_SECRET_ACCESS_KEY
     for any valid AWS account. It will be accessing builds.emberjs.com in read only mode, which is public.
7. In the repo directory, run `node index`
