### ISSUE TITLE
Finish TravisCI setup

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-jsonapi-docs#11]
> From https://github.com/ember-learn/ember-jsonapi-docs/pull/10

Finishes https://github.com/ember-learn/ember-api-docs/issues/66

Things that requires travis org admin access,

- [x] Enable travis for this repo (done by @acorncom)

Set the following,

```
travis env set AWS_ACCESS_KEY_ID "$AWS_ACCESS_KEY_ID"
travis env set AWS_SECRET_ACCESS_KEY "$AWS_SECRET_ACCESS_KEY"
travis env set COUCH_USERNAME "$COUCH_USERNAME"
travis env set COUCH_PASSWORD "$COUCH_PASSWORD"
```

- [ ] Replace the **COUCH_URL** in .travis.yml with actual db
- [ ] If the target couch db is a new one, we need to populate it with at least v1 docs since generating docs for both v1.x and v2.x takes more than 50mins which is the max period for travis builds.

**Comment by acorncom** [comment]
Status update here: just gave @sivakumar-kailasam access to what I'm aiming to have be the official Couch account (https://emberjs.cloudant.com/).  He's going to work on some things there and I'll work on tracking down AWS details

**Comment by sivakumar-kailasam** [comment]
Populating the docs from my local partially for 1.x docs to begin with.

**Comment by sivakumar-kailasam** [comment]
I've indexed v1 docs from my machine. I need help with,

- [x] Enabling cron on a daily/hourly basis so that new docs will get published w/o us having to do anything.
- [x] Setting the ember-learn team's encrypted AWS creds for travis

**Comment by sivakumar-kailasam** [comment]
@acorncom I've replaced my personal keys for AWS since core would anyway update all keys related to cloudant, heroku and AWS. So #12 is good to merge. Do enable the cron for an hourly run though via travis UI (can't be enabled via config)

**Comment by sivakumar-kailasam** [comment]
The generator code & travis works off my s3 bucket for the generated docs. Need to get the core team to give us a s3 bucket & setup keys for us

**Comment by acorncom** [comment]
S3 bucket and keys is on the agenda for a conversation with Godfrey Chan on Friday

**Comment by sivakumar-kailasam** [comment]
Travis CI setup is over for this repo. Tracking new doc publishes via #30
