### ISSUE TITLE
some attributes and relationships share a same name

### ISSUE THREAD

**Issue by MartinMalinda** [ember-learn/ember-jsonapi-docs#13]
In this JSON, `classes` are both an attribute and a relationship. In ember-data, this will result in not being able to have `classes: attr()` and `classes: hasMany()` at the same time and maybe other issues.

![screen shot 2016-12-14 at 19 12 30](https://cloud.githubusercontent.com/assets/9468793/21194746/500c72aa-c231-11e6-8ce3-a6dab0b41105.png)

I think this is a blocker for ember-learn/ember-api-docs#122. Classes will have to be sideloaded and private ones filtered out.

**Comment by toddjordan** [comment]
I think this may have been fixed by #23 @MartinMalinda can you confirm?

**Comment by MartinMalinda** [comment]
This is fixed. I've totally missed this earlier 😅
