### ISSUE TITLE
Fixing hardcoded links

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-jsonapi-docs#24]
There are links hardcoded in the class descriptions that point to the existing url such as `/api/data/classes/DS.ConflictError.html`. These need to be corrected to point to the correct versioned url.

**Comment by sivakumar-kailasam** [comment]
https://github.com/ember-learn/ember-jsonapi-docs/blob/2f180d44c4a6571811fa1972f890146cc4380576/lib/markup.js#L50 we could lookup links here and replace tehm with the path from the api docs ember app.

**Comment by toddjordan** [comment]
@sivakumar-kailasam how high a priority is this?  is it blocking any current functionality?

**Comment by sivakumar-kailasam** [comment]
@toddjordan Not a blocker since we handle those redirects. Tracked to ensure that its being fixed.

**Comment by toddjordan** [comment]
Closing since we are handling the case, and are not planning a fix anytime soon.  If it becomes an issue again we can still address.
