### ISSUE TITLE
Versioning of docs

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-jsonapi-docs#31]
We mark docs as immutable in the current iteration in s3 so that we don't even need service workers or app cache to help us cache those content. But in reality the content of certain files do mutate over time. For eg., the projects versions file will change whenever there's new version of ember or ember-data released.

To solve this we'll have to revision file names so that we don't have to worry about clashes ever again. This would involve adding a revision attribute to existing models that indicates the rev file name.

**Comment by acorncom** [comment]
@toddjordan FYI on the above ( @sivakumar-kailasam and I were discussing it last night)  Seems like our largest issue here is going to be how we handle caching (or rather flushing the cache) for the main `/ember/projects/ember.json` file.  If that file controls what sub-versions we display and we've cached it heavily, but then a new version of Ember comes out ... 😀

**Comment by sivakumar-kailasam** [comment]
As an FYI, this is now solvable temporarily via purging fastly cache.

**Comment by sivakumar-kailasam** [comment]
revving guides seeming to be working for us since we've gone live. So closing this in favor of that..
