### ISSUE TITLE
Missing API docs

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-jsonapi-docs#43]
- ~~on()~~
- [x] http://emberjs.com/api/classes/Ember.Debug.html#method_registerDeprecationHandler
       _separate module annotation from method in deprecate.js_
- [x] http://emberjs.com/api/classes/Ember.Object.html#method_incrementProperty and toggleProperty
       _update `@extends` annotation on EmberObject to be {Observable} and not {Ember.Observable}_
- ~~http://emberjs.com/api/classes/Ember.Enumerable.html~~
- [x] http://emberjs.com/api/classes/Ember.Object.html#method_reopen and reopenClass
       _add `@static` and `@for @ember/object` to method annotations_
- ~~http://emberjs.com/api/classes/Ember.Helper.html#method_helper~~
- ~~http://emberjs.com/api/classes/Ember.String.html#method_htmlSafe~~
- ~~http://emberjs.com/api/classes/Ember.Test~~
- ~~get (not Ember.get)~~
- [x] observer function `@ember/object`

Please comment with anything else that can't be found

**Comment by toddjordan** [comment]
htmlSafe:
![image](https://user-images.githubusercontent.com/3609063/31611589-b3543cb2-b24a-11e7-8a79-4f5bcee234a5.png)

**Comment by toddjordan** [comment]
helper (under package `@ember/component`)
![image](https://user-images.githubusercontent.com/3609063/31611618-cedf11f0-b24a-11e7-8bcb-5227d3b04ef0.png)

**Comment by toddjordan** [comment]
Ember.Test https://emberjs.com/api/ember/2.16/classes/Ember.Test

**Comment by toddjordan** [comment]
`on()`  `@ember/object/evented`
![image](https://user-images.githubusercontent.com/3609063/31611868-c81978f0-b24b-11e7-8afa-42d6e69b42da.png)

**Comment by Turbo87** [comment]
@jenweber all other methods related to `Ember.Object.get()` are also missing: `set`, `setProperties`, `getProperties`, `toggleProperty`, ...

**Comment by toddjordan** [comment]
@Turbo87 
![image](https://user-images.githubusercontent.com/3609063/31611969-306a72ba-b24c-11e7-8fec-74fe0d5c490b.png)

**Comment by toddjordan** [comment]
`incrementProperty`: https://emberjs.com/api/ember/2.16/classes/Observable/methods/incrementProperty?anchor=incrementProperty

**Comment by toddjordan** [comment]
Ember.Enumerable is private.  If you toggle on private classes its there: https://emberjs.com/api/ember/2.16/classes/Enumerable

**Comment by Turbo87** [comment]
@toddjordan what you linked is unrelated. I'm talking about the methods, not the global `Ember.get()` functions

**Comment by toddjordan** [comment]
@Turbo87 correct.  They are functions of Observable, listed in this item.  The `@extends` annotation of EmberObject needs updating.
```
http://emberjs.com/api/classes/Ember.Object.html#method_incrementProperty and toggleProperty
update @extends annotation on EmberObject to be {Observable} and not {Ember.Observable}
```

**Comment by toddjordan** [comment]
Added fixes to https://github.com/emberjs/ember.js/pull/15716

**Comment by toddjordan** [comment]
cases identified here are fixed
