### ISSUE TITLE
`since` attribute always points to current version

### ISSUE THREAD

**Issue by knownasilya** [ember-learn/ember-jsonapi-docs#53]
Related to https://github.com/ember-learn/ember-api-docs/pull/426

Looks like a default is set or maybe just the wrong value passed down?

cc @locks

**Comment by knownasilya** [comment]
@toddjordan maybe tagging this with 'hacktoberfest'?

**Comment by toddjordan** [comment]
I'm gonna pick this up this weekend.  Wish me luck ;-)

**Comment by sivakumar-kailasam** [comment]
![image](https://user-images.githubusercontent.com/604117/55271865-29413c00-52da-11e9-99a6-71b076eb9c37.gif)

**Comment by toddjordan** [comment]
fixt... new runs will have since if it exists.  Plan to do a full regen in the next week or two.  Will not enable the UI part of the fix until the full regen, as old releases will show only current version.

**Comment by toddjordan** [comment]
See #61
