### ISSUE TITLE
Need to account for `reopen` and `@for`

### ISSUE THREAD

**Issue by Gaurav0** [ember-learn/ember-jsonapi-docs#57]
Looking at https://github.com/emberjs/ember.js/issues/16247 and at the source of https://github.com/emberjs/ember.js/blob/v3.0.0/packages/ember-routing/lib/ext/controller.js

The underlying issue is that ember-jsonapi-docs do not account for the use of `reopen` and `@for` in source documentation.

**Comment by Gaurav0** [comment]
The fix is likely to be very similar to the one for `uses` here:
https://github.com/ember-learn/ember-jsonapi-docs/blob/d8c217d19f5f68cf03cec9f82e46a9a9722a4e94/lib/add-inherited-items.js#L42-L44

**Comment by toddjordan** [comment]
`@for` still works.  We just need to change it back from `@for ControllerMixin` to `@for Ember.ControllerMixin`

**Comment by toddjordan** [comment]
Will track in ember-learn/ember-api-docs#468
