### ISSUE TITLE
rearrange and polish some of the README.md content

### ISSUE THREAD

**Issue by ghost** [ember-learn/ember-jsonapi-docs#71]
As a developer working on documentation locally, I am interested in just this task. (e.g. I have no kingdom keys). Reading through the README.md and following the steps was a bit confusing at first. I can submit PRs based on any consensus for the points below.  

> ember-jsonapi-docs is for turning code comments in ember.js into json api compliant data for use in various applications seeking to use the Ember API.

- seems this line should say ember-data as well? 

- I propose moving the [testing API docs locally](https://github.com/ember-learn/ember-jsonapi-docs#generating-api-documentation-and-testing-api-docs-locally) steps to one of the first sections, or breaking it out into another focused markdown file. e.g. quickstart to build API docs locally.
- Steps 3, 4, and 5 seem to have duplicate content themselves. "to the ember-api-docs directory & runs this app", step 4 says run the app in addition to step 5. 

Is there a difference between running "this app" versus serving up the local transformed yuidocs with `yarn server`? Either way it seems we could remove the first part of line 5 but additional clarity in these steps would reduce confusion.

**Comment by sivakumar-kailasam** [comment]
Thanks for the feedback @efx, will gladly accept a PR with all of these changes.
