### ISSUE TITLE
ember data will no longer generate docs in a production build

### ISSUE THREAD

**Issue by Gaurav0** [ember-learn/ember-jsonapi-docs#78]
Related: #74 

After this change:
https://github.com/emberjs/data/blob/fbf06f8ba23cc3a41c931e344648e6042ad2b233/packages/-ember-data/yuidoc.json#L6

(which will go into Ember 3.16)

This line will no longer work in ember-jsonapi-docs:
https://github.com/ember-learn/ember-jsonapi-docs/blob/5c3d9d81107ef4ec8e1fe016de8be3c3c214121b/generate-local.js#L62

We will have to do something different for versions of Ember Data before and after 3.16, because there will no longer be a single command that will generate docs in all versions of Ember Data..

cc @sivakumar-kailasam @runspired @efx

**Comment by sivakumar-kailasam** [comment]
Fixed in https://github.com/ember-learn/ember-jsonapi-docs/commit/b61a26796095fc397893c2f282060b1a76dbfc31 & this should be backward compatible.
